### ISSUE TITLE
Разбить на packages

### ISSUE THREAD

**Issue by matklad** [Ivan-Veselov/atum#47]
Сейчас в `ru.spbau.mit.atum` 100500 классов, и совершенно не понятно, в каком порядке их следует читать, и куда смотреть, если хочется сделать X. 

Хорошо, когда структура директорий проекта (и, соответственно, пакетов в Java) позволяет понять архитектуру приложения. 

В данном случае видимо можно выделить как минимум следующие подпакеты 

* `ui` -- все activities

* `timte` -- внутренняя модель с интервалами и фильтрами, не сильно зависящая от android. 

* может быть что-то отдельное про синхронизацию/настройки.

**Comment by Ivan-Veselov** [comment]
bb0f3b4e87eca9ec8aef97c533d21aefac0f569c

**Comment by matklad** [comment]
Дааа, теперь можно посмотреть на https://github.com/Ivan-Veselov/atum/tree/master/app/src/main/java/ru/spbau/mit/atum и сразу понять, что происходит!

У такой организации есть ещё бонус: можно посмотреть на импорты какого-нибудь класса из `model`, увидеть, например, `import ...ui.Foo` и понять, что что-то пошло не так. Вообще, смотреть на импорты очень полезно, чтобы понять зависимости между кусками кода.

**Comment by matklad** [comment]
:+1:
